services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin  
      POSTGRES_DB: meubanco     
    ports:
      - "7500:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: